"""init corrections

Revision ID: 36598d41b10e
Revises: 3692a797bc26
Create Date: 2025-10-01 17:37:53.702580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '36598d41b10e'
down_revision: Union[str, Sequence[str], None] = '3692a797bc26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field_corrections',
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('current_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('correct_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['contracts.document_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id', 'field_name', 'created_at')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('field_corrections')
    # ### end Alembic commands ###
