"""init compliance control

Revision ID: 5c6721071d81
Revises: 36598d41b10e
Create Date: 2025-11-18 20:49:55.983237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c6721071d81'
down_revision: Union[str, Sequence[str], None] = '36598d41b10e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('compliance_check_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'compliance_check_json')
    # ### end Alembic commands ###
